[wip] Added database config and connection pool
akurey/animal-rescue-backend pull request #19
Opened 2022-05-26 19:37 UTC by lindsaymb15

DB config and connection pool added.

2022-05-26 21:06 UTC, javalosak commented on database/database.go
> +	host     = os.Getenv("HOST")
```DB_HOST```

2022-05-26 21:07 UTC, javalosak commented on database/database.go
> +	host     = os.Getenv("HOST")
Agregarlos al readme

2022-07-06 22:36 UTC, asanchezhed requested changes

2022-07-06 22:36 UTC, asanchezhed commented on database/database.go
> +	database.DB().SetMaxIdleConns(20)
Can we set an env variable for these values?

2022-07-06 22:36 UTC, asanchezhed commented on README.md
> +- add a .env file on the root folder with the DB config variables (DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME)
can we add an env.example file with the variable names we use on the project so every time a new dev comes, they will only need to fill out the file with their credentials?

2022-07-07 19:19 UTC, asanchezhed approved these changes

2022-07-14 20:09 UTC, merged