Arb 34
akurey/animal-rescue-backend pull request #50
Opened 2022-09-13 23:09 UTC by enavarroAK

### Summary
> Created the endpoint to obtain the animal record.

### Changelog
- Created endpoint to get the animal record
- Created the animal record type.

### Ticket 
https://github.com/akurey/animal-rescue-backend/issues/34

### Solution
- Created the endpoint to get one animal record.

### Considerations
The endpoint uses AFN_GetAnimalReport since it was easier to get the returning data.

Example response:
`{
    "response": [
        {
            "id": 2,
            "IdAnimal": 0,
            "AnimalName": "",
            "ScientificName": "",
            "ConservationStatusName": "",
            "Abbreviaton": "NT",
            "ClassificationName": "",
            "Fields": "{\"Sexo\": \"Hembra\", \"Color\": \"Amarillo\", \"Dirección\": \"{\\\"Canton\\\": \\\"Osa\\\", \\\"Distrito\\\": \\\"Bahia Drake\\\", \\\"Direccion\\\": \\\"PN Corcovado\\\", \\\"Provincia\\\": \\\"Puntarenas\\\"}\", \"Procedencia\": \"Osa\", \"Número de identificación (CHIP)\": \"67890\"}"
        }
    ]
}`

2022-09-14 00:42 UTC, rnavarroSF requested changes
Couple of comments

2022-09-14 00:42 UTC, rnavarroSF commented on .env
> +DB_HOST="otto.db.elephantsql.com"
```suggestion
DB_HOST="ec2-52-3-60-53.compute-1.amazonaws.com"
```

2022-09-14 00:42 UTC, rnavarroSF commented on .env
> +DB_NAME="rutelazj"
```suggestion
DB_USER="xybvtiinusasyh"
DB_PASSWORD="389e9dac39c30290ed036e62362ec3e7cc435f0432f3b2cdce1bf6125bb61ae3"
DB_NAME="d63vklqd241lbk"
```

Lets revert this until dicember

2022-09-14 00:42 UTC, rnavarroSF commented on controllers/report.go
> +	var report []*models.AnimalReport
Doesn't need to be an array, we will only be getting one record

2022-11-03 22:58 UTC, pdinarte approved these changes
🚀

2022-11-10 21:02 UTC, rnavarroSF approved these changes
Thanks so much for everything! 🚀

2022-11-10 21:53 UTC, merged