Login Implementation
akurey/animal-rescue-backend pull request #58
Opened 2022-12-07 18:02 UTC by nortega12

### Summary
> We needed that the users were able to log in.

### Changelog
- Added a user model.
- Added token and refresh token columns in users table (add_new_user_columns.sql).
- Added  AFN_AddUser function. 
- Added AFN_GetUser function.
- Added AFN_UpdateUser function.
- Added the user controller.
- Added a tokenHelper.go file to generate tokens.
- Added the sign up and sign in endpoints.

### Ticket 
https://github.com/akurey/animal-rescue-backend/issues/57

2022-12-07 23:42 UTC, rnavarroSF requested changes

2022-12-07 23:42 UTC, rnavarroSF commented on controllers/user.go
> +	Password     string `json:"password" binding:"required,min=6"`
How do we receive the password here?
If it's a plain string with the password, could someone read that somewhere?

2022-12-07 23:42 UTC, rnavarroSF commented on controllers/user.go
> +		if user.Username == ""{
Does this happen? Wouldn't the request be invalid because LoginUserRequest has username as required?:
`Username    string json:"username" binding:"required,alphanum"`

2022-12-07 23:42 UTC, rnavarroSF commented on controllers/user.go
> +		ctx.JSON(http.StatusInternalServerError, gin.H{"error": msg})
```suggestion
		ctx.JSON(http.StatusUnauthorized, gin.H{"error": msg})
```

2022-12-07 23:42 UTC, rnavarroSF commented on controllers/user.go
> +	user, err, msg = GetUser(ctx, body.Username)
Why do you call this here again?
It's on line 147 as well

2022-12-07 23:42 UTC, rnavarroSF commented on database/016 - AFN_AddUser.sql
> +	pname varchar(50),
Can you make these `pName` with the second letter in uppercase?
Also, can all the reserved words be in uppercase?, ei. VARCHAR

2022-12-07 23:42 UTC, rnavarroSF commented on database/016 - AFN_AddUser.sql
> +		(pname,plastName,pusername,pemail,ppassword,pidentification,psinac, ptoken, prefresh_token)
```suggestion
		(pName, pLastName, pUsername, pEmail, pPassword, pIdentification, pSinac, pToken, pRefreshToken)
```

2022-12-07 23:42 UTC, rnavarroSF commented on database/016 - AFN_AddUser.sql
> +	prefresh_token varchar(500)
```suggestion
	pRefreshToken VARCHAR(500)
```

2022-12-07 23:42 UTC, rnavarroSF commented on database/016 - AFN_AddUser.sql
> +	FROM "AP_Users" AR;
What does AR stand for?

2022-12-07 23:42 UTC, rnavarroSF commented on database/017 - AFN_GetUser.sql
> +CREATE OR REPLACE FUNCTION AFN_GetUser(pUserName varchar)
```suggestion
CREATE OR REPLACE FUNCTION AFN_GetUser(pUserName VARCHAR(100))
```

2022-12-07 23:42 UTC, rnavarroSF commented on database/017 - AFN_GetUser.sql
> +    AR.email Email, AR.password Passwordd, AR.identification Identification, AR.sinac_registry Sinac, AR.token Token, AR.refresh_token RefreshToken
```suggestion
    SELECT AR.id ID, AR.first_name First_name, AR.last_name Last_name, AR.username, 
    AR.email Email, AR.password Password, AR.identification Identification, AR.sinac_registry Sinac, AR.token Token, AR.refresh_token RefreshToken
```

2022-12-07 23:42 UTC, rnavarroSF commented on database/018 - AFN_UpdateUser.sql
> +	prefresh_token varchar
same

2022-12-07 23:42 UTC, rnavarroSF commented on database/018 - AFN_UpdateUser.sql
> +        FROM "AP_Users" UT
What does UT stand for?

2022-12-07 23:42 UTC, rnavarroSF commented on database/database.go
> +	psqlConnInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable ", DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME)
What does this do?

2022-12-07 23:42 UTC, rnavarroSF commented on helpers/tokenHelper.go
> +func GenerateAllTokens(username string) (signedToken string, signedRefreshToken string, err error){
Would `GenerateUserTokens` be a better name for this?

2022-12-07 23:42 UTC, rnavarroSF commented on helpers/tokenHelper.go
> +			ExpiresAt: time.Now().Local().Add(time.Hour * time.Duration(168)).Unix(),
Love these time settings! ❤️
Can we move them to be an ENV_VAR?

2022-12-07 23:42 UTC, rnavarroSF commented on helpers/tokenHelper.go
> +	return token, refreshToken, err
If you're `panic`-ing if err isn't nil, why send it over here if it's always going to be nil?

2022-12-08 14:59 UTC, nortega12 commented on controllers/user.go
> +	Sinac_registry string `json:"sinac_registry" binding:"required"`
Yes it is required, should I change it?

2022-12-08 15:02 UTC, nortega12 commented on controllers/user.go
> +	Password     string `json:"password" binding:"required,min=6"`
this is like the request body, so the user signs up and puts the plain string but immediately when the user signs up it is converted to a hash password

2022-12-08 15:08 UTC, nortega12 commented on controllers/user.go
> +		if user.Username == ""{
This getUser is used to find a user in the db with the same username, so if it isn't found then the body is empty, so it returns the "Username not found" message in the error. `msg = fmt.Sprintf("Username not found")`

2022-12-08 17:56 UTC, nortega12 commented on controllers/user.go
> +	user, err, msg = GetUser(ctx, body.Username)
Because I have to get the new tokens back to put them in the success response, I can get them from line 160 but I get the user to confirm that the tokens were changed correctly

2022-12-08 18:17 UTC, nortega12 commented on database/016 - AFN_AddUser.sql
> +	FROM "AP_Users" AR;
my bad, I'll change it

2022-12-08 18:25 UTC, nortega12 commented on database/018 - AFN_UpdateUser.sql
> +        FROM "AP_Users" UT
I'll change it

2022-12-08 18:26 UTC, nortega12 commented on database/database.go
> +	psqlConnInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable ", DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME)
there was an error when running the project, Jona told me that this fixed it

2022-12-12 15:58 UTC, rnavarroSF commented on controllers/user.go
> +	Sinac_registry string `json:"sinac_registry" binding:"required"`
Yes please 🙏🏼

2022-12-13 23:00 UTC, rnavarroSF commented on database/016 - AFN_AddUser.sql
> +	FROM "AP_Users" AU;
This returns all the users, wondering if you wanted to filter it by userId?

2022-12-14 16:09 UTC, rnavarroSF approved these changes
Thanks so much for this! 🚀

2022-12-14 16:50 UTC, merged